### ISSUE TITLE
CSS files parsed as JS

### ISSUE THREAD

**Issue by Robertlonardi** [joeyism/node-minify-all#1]
Hello,

I'm trying to use the minify-all extension to minify JS and CSS files in the deploy script. The extensions works great for JS files, but when it reaches some CSS files, it try to parse them and gives me a parsing error (It is trying to parse the CSS files as Javascript with "eval" method, and of course it throws an error). Am i doing something wrong or is just a bug?

Thanks in advance

**Comment by joeyism** [comment]
Hi Robert,

node-minify-all depends on node-minify, and uses _uglify_ to minify. If that doesn't work, you can specify {_type: 'sqwish'_} in options, as sqwish is used specifically to minify CSS files. You can see the other types of minify library [here](https://www.npmjs.com/package/node-minify)
